server {
    listen 80;

    location = / {
        return 301 /quit/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /quit/index.html;
    }

    error_page 404 /quit/index.html;
}
